include:
  - path: ./compose-infra/mongo.yaml
  - path: ./compose-infra/kafka.yaml
  - path: ./compose-infra/mysql.yaml
  - path: ./compose-infra/redis.yaml
  - path: ./compose-infra/infra.yaml

services:
  metadata-server:
    build:
      context: metadata-server
      dockerfile: Dockerfile
      network: host
    ports:
      - "${PORT_METADATA_SERVER}:${PORT_METADATA_SERVER_INTERNAL}"
    environment:
      - SERVER_PORT=${PORT_METADATA_SERVER_INTERNAL}
      - MONGO_DB_URI=mongodb://mongo1:${PORT_MONGO_DB_PRIMARY_INTERNAL},mongo2:${PORT_MONGO_DB_SECONDARY_1_INTERNAL},mongo3:${PORT_MONGO_DB_SECONDARY_2_INTERNAL}/${MONGO_DB_METADATA_DB_NAME}
    volumes:
      - ./metadata-server/.env:/app/.env
    depends_on:
      mongo1: 
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    develop:
      watch:
        - path: ./metadata-server/build.gradle
          action: rebuild
        
        - path: ./metadata-server/.env
          action: rebuild

        - path: ./metadata-server/build/classes/java/main
          action: rebuild
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT_METADATA_SERVER_INTERNAL}/health-check | grep -i up || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 40s
  
  python-data-generator:
    build:
      context: dataset-generation
      dockerfile: Dockerfile
      network: host
    environment:
      - METADATA_SERVER_URL=http://metadata-server:${PORT_METADATA_SERVER_INTERNAL}
      - SCHEMA_REGISTRY_URL=http://schema-registry:${PORT_SCHEMA_REGISTRY_INTERNAL}
      - KAFKA_URL=broker:29092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    volumes:
      - ./dataset-generation/.env:/app/.env
      - ./dataset-generation/docker-logs:/app/logs
      - ./dataset-generation/pythonScriptConfig.json:/app/pythonScriptConfig.json
    depends_on:
      metadata-server:
        condition: service_healthy
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    develop:
      watch:
        - path: ./dataset-generation/main.py
          target: /app/main.py
          action: sync+restart
        - path: ./dataset-generation/helpers
          target: /app/helpers
          action: sync+restart
        - path: ./dataset-generation/resources
          target: /app/resources
          action: sync+restart
  
  words-server:
    build:
      context: words-server
      dockerfile: Dockerfile
      args:
        SCHEMA_REGISTRY_URL: http://localhost:${PORT_SCHEMA_REGISTRY}
      network: host
    ports:
      - "${PORT_WORDS_SERVER}:${PORT_WORDS_SERVER_INTERNAL}"
    environment:
      - SERVER_PORT=${PORT_WORDS_SERVER_INTERNAL}
      - MYSQL_URL=jdbc:mysql://mysql:${PORT_MYSQL_INTERNAL}/${MYSQL_WORDS_DB_NAME}
      - SCHEMA_REGISTRY_URL=http://schema-registry:${PORT_SCHEMA_REGISTRY_INTERNAL}
      - MYSQL_DATASOURCE_USERNAME=${MYSQL_WORDS_SERVER_USER}
      - MYSQL_DATASOURCE_PASSWORD=${MYSQL_WORDS_SERVER_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - REDIS_HOST=redis
      - REDIS_PORT=${PORT_REDIS_INTERNAL}
    volumes:
      - ./words-server/.env:/app/.env
    depends_on:
      mysql: 
        condition: service_healthy
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      metadata-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    develop:
      watch:
        - path: ./words-server/build.gradle
          action: rebuild
        
        - path: ./words-server/.env
          action: rebuild

        - path: ./words-server/build/classes/java/main
          action: rebuild
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT_WORDS_SERVER_INTERNAL}/health-check | grep -i up || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 40s