services:
  mongo1:
    image: mongo:8.0.11
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - ${PORT_MONGO_DB_PRIMARY}:${PORT_MONGO_DB_PRIMARY_INTERNAL}
    volumes:
      - "mongo1_data:/data/db"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    healthcheck:
      test: mongosh --port ${PORT_MONGO_DB_PRIMARY_INTERNAL} --eval "db.hello()" --quiet
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 2s
  mongo2:
    image: mongo:8.0.11
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - ${PORT_MONGO_DB_SECONDARY_1}:${PORT_MONGO_DB_SECONDARY_1_INTERNAL}
    volumes:
      - "mongo2_data:/data/db"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    healthcheck:
      test: mongosh --port ${PORT_MONGO_DB_SECONDARY_1_INTERNAL} --eval "db.hello()" --quiet
      interval: 31s
      timeout: 5s
      retries: 10
      start_period: 2s
  mongo3:
    image: mongo:8.0.11
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - ${PORT_MONGO_DB_SECONDARY_2}:${PORT_MONGO_DB_SECONDARY_2_INTERNAL}
    volumes:
      - "mongo3_data:/data/db"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    healthcheck:
      test: mongosh --port ${PORT_MONGO_DB_SECONDARY_2_INTERNAL} --eval "db.hello()" --quiet
      interval: 32s
      timeout: 5s
      retries: 10
      start_period: 2s
  mongo-init:
    image: mongo:8.0.11
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c" ]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    command: >
      "
       mongosh --host mongo1 --port ${PORT_MONGO_DB_PRIMARY_INTERNAL} --eval \"
         try {
           let status = rs.status();
           print('Replica set already initialized.');
         } catch (e) {
          if (e.message.includes('no replset config has been received')) {
            print('Initializing replica set...');
            let res = rs.initiate({
              _id: 'rs0',
              members: [
                {_id: 0, host: 'mongo1:${PORT_MONGO_DB_PRIMARY_INTERNAL}', priority: 2},
                {_id: 1, host: 'mongo2:${PORT_MONGO_DB_SECONDARY_1_INTERNAL}', priority: 1},
                {_id: 2, host: 'mongo3:${PORT_MONGO_DB_SECONDARY_2_INTERNAL}', priority: 1}
              ]
            });
            if (res.ok !== 1) { throw new Error('Replica set initiation failed'); }
          } else {
            throw e;
          }
        }
       \" &&
       echo \"Waiting for primary election...\" &&
       mongosh --host mongo1 --port ${PORT_MONGO_DB_PRIMARY_INTERNAL} --eval \"
         while (!db.hello().isWritablePrimary) { 
           sleep(500); 
         }
       \" &&
       echo \"Primary elected! Creating users...\" &&
       mongosh --host mongo1 --port ${PORT_MONGO_DB_PRIMARY_INTERNAL} --eval \"
         db = db.getSiblingDB('admin');
         let adminUser = db.getUser('${MONGO_DB_ROOT_USER}');
         if (!adminUser) {
            print('Creating root user...');
            db.createUser({
              user: '${MONGO_DB_ROOT_USER}',
              pwd: '${MONGO_DB_ROOT_PASS}',
              roles: [
                { role: 'root', db: 'admin' }
              ]
            });
         } else {
            print('Root user already exists.');
         }
         db = db.getSiblingDB('${MONGO_DB_METADATA_DB_NAME}');
         let appUser = db.getUser('${MONGO_DB_METADATA_SERVER_USER}');
         if (!appUser) {
            print('Creating metadata server user...');
            db.createUser({
              user: '${MONGO_DB_METADATA_SERVER_USER}',
              pwd: '${MONGO_DB_METADATA_SERVER_PASSWORD}',
              roles: [
                { role: 'readWrite', db: '${MONGO_DB_METADATA_DB_NAME}' }
              ]
            });
          } else {
           print('Metadata server user already exists.');
         }
       \" &&
       echo \"Completed Mongo init\""
       

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_ROOT_USER}:${MONGO_DB_ROOT_PASS}@mongo1:${PORT_MONGO_DB_PRIMARY_INTERNAL},mongo2:${PORT_MONGO_DB_SECONDARY_1_INTERNAL},mongo3:${PORT_MONGO_DB_SECONDARY_2_INTERNAL}/admin?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - ${PORT_MONGO_EXPRESS}:${PORT_MONGO_EXPRESS_INTERNAL}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    depends_on:
      mongo1: 
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy

volumes:

  mongo1_data:
  mongo2_data:
  mongo3_data:
