services:
  mysql:
    image: mysql:lts-oraclelinux9
    ports:
      - ${PORT_MYSQL}:${PORT_MYSQL_INTERNAL}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_WORDS_DB_NAME}
      MYSQL_USER: ${MYSQL_WORDS_SERVER_USER}
      MYSQL_PASSWORD: ${MYSQL_WORDS_SERVER_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -p${MYSQL_ROOT_PASSWORD} -D words -e 'SELECT 1 FROM nodes LIMIT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

volumes:
  mysql-data: