services:
  redis:
    image: redis:alpine3.23
    command: --port ${PORT_REDIS_INTERNAL}
    volumes:
      - redis-data:/data
    ports:
      - ${PORT_REDIS}:${PORT_REDIS_INTERNAL}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  redis-data: